### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by Chamelpower98** [Z3DR/MM3D_Randomizer#116]
So with the new skull rando there is a dupe glitch if you kill a skull collect for example a sword then song of time then you can collect the sword again

**Comment by PhlexPlexico** [comment]
As @RandoZLink has stated this has been reported and patched already, thanks for the heads up though!

**Comment by Chamelpower98** [comment]
Oh ok sorry about that

PhlexPlexico ***@***.***> schrieb am Mi., 23. Okt. 2024,
22:50:
