### ISSUE TITLE
Southern Swamp is not showing map even if purchased

### ISSUE THREAD

**Issue by johnnyq3** [Z3DR/MM3D_Randomizer#120]
Southern swamp is not showing the map in the Southern swamp map, it will show it in the connecting path, around woodfall Temple, and Deku Palace.

![IMG_2924](https://github.com/user-attachments/assets/7bfca9ce-007e-4492-a170-0bacecfacc50)
![IMG_2926](https://github.com/user-attachments/assets/f44cc4af-367b-4228-aac3-092fe0c9a05c)

**Comment by PhlexPlexico** [comment]
When posting an issue, please post the version of the randomizer you are running with the 6 alphanumeric string that's associated with it, as well as where you retrieved the item please. Otherwise it's going to take more time to figure out how to reproduce it.

Thanks!

**Comment by johnnyq3** [comment]
Map is showing fine now after a Song of Time for a 3 day cycle, I bought the map from Tingle.

I am using v1.4.2-975651
