### ISSUE TITLE
No Map on Romani Ranch

### ISSUE THREAD

**Issue by johnnyq3** [Z3DR/MM3D_Randomizer#28]
No map is showing for the main Romani ranch, I am using the 1.1 patch version for the randomizer, the map is showing find for other locations for Milk road, just not Romani Ranch proper, I bought the map from Tingle.  

Seed Hash:
Powder Keg
Magic Bean
Deku Princess
Letter to Mama
Hero's Bow

![IMG_2172](https://github.com/Z3DR/MM3D_Randomizer/assets/58367068/f1b6da52-a9ad-4285-8dd6-1f9c4e86a719)

**Comment by PhlexPlexico** [comment]
Hi!

This will be fixed next release, per this PR https://github.com/Z3DR/MM3D_Randomizer/pull/27

Thanks!
