### ISSUE TITLE
Non randomized zora eggs not allowing seed to generate 

### ISSUE THREAD

**Issue by DJNETTLES14** [Z3DR/MM3D_Randomizer#37]
If the zora eggs are non randomized then you can’t generate a seed

**Comment by PhlexPlexico** [comment]
I'm sorry, could you please explain further? Zora eggs cannot be randomized as of right now, as far as I know.

Thanks!

**Comment by DJNETTLES14** [comment]
When I take them out of the randomized pool it say failed to load seed and won’t work

**Comment by PhlexPlexico** [comment]
Ah, well they currently are not randomized locations, so you can leave them in for now, they will still be at the default locations.

**Comment by PhlexPlexico** [comment]
Since we have not currently implemented this, will close this issue. Just remove the Zora eggs from your excluded location and it should generate.
