### ISSUE TITLE
Turning off randomizer

### ISSUE THREAD

**Issue by DJNETTLES14** [Z3DR/MM3D_Randomizer#39]
How do I turn it off so I can play normally

**Comment by PhlexPlexico** [comment]
As it says in the [README](https://github.com/Z3DR/MM3D_Randomizer?tab=readme-ov-file#on-3ds-console-with-luma3ds)

> Power on your 3DS while holding the SELECT key to launch the Luma3DS menu. Make sure that Enable game patching is turned on, then press START to save and launch the home menu. You only have to do this once.

You simply do the reverse. Press SELECT while your 3DS is booting and Disable game patching.

**Comment by PhlexPlexico** [comment]
If you have any other questions feel free to pop by the [discord](https://discord.com/invite/73ZNdjbfFp)!
