### ISSUE TITLE
Certain Repeatable Items Not Triggering

### ISSUE THREAD

**Issue by DiabloThePoet** [Z3DR/MM3D_Randomizer#40]
I received a powder keg from the peahat grotto in Termina Field, which is listed as a repeatable item in the item locations checklists logs, but after returning to the grotto on a new 3-day cycle to get another powder keg, I was instead given a blue rupee. This is the only instance of this so far that I have noticed, but there may be other instances that I just haven't noticed or realized. I am not as familiar with all of the chest locations and usual loot as I am with OOT. 

Also, I am playing this on my actual 3ds using the homebrew app.

**Comment by PhlexPlexico** [comment]
Please list the version you are currently running, or the spoiler log.

This has already been addressed and will be fixed in an upcoming release!

Thanks!

**Comment by Scathlon** [comment]
Here is the Logoc behind it:

If you got the Poweder Keg once, you can buy it in the bomb shop. ( From the Goron )

I had the same issue but you can buy the poweder keg instead ( worked on multiple Playthprughs on different randos )

**Comment by PhlexPlexico** [comment]
The one thing to avoid though is to make sure you do not do the powder keg quest first as well, as the item check is currently bugged. That will full on lock you out of the powder keg. So beware of that!

**Comment by PhlexPlexico** [comment]
Fixed as of https://github.com/Z3DR/MM3D_Randomizer/pull/42
