### ISSUE TITLE
Received Multiple Items From Gorman Special Milk Side Quest Upon Multiple Completions

### ISSUE THREAD

**Issue by DiabloThePoet** [Z3DR/MM3D_Randomizer#43]
Upon the first time completing the Gorman special milk quest, I was given the map to Romani Ranch. Upon completing the quest for a second time I was given the Keaton mask. Looking at my item checklist, it says I got the Keaton mask from the Gradnma long story quest, but I have not done that quest at all yet since I do not have the all night mask.

Current Version: v1.2.1

Seed Hash:
Letter To Mama
Deku Princess
Bomber's Notebook
Bombchu
Blast Mask

**Comment by PhlexPlexico** [comment]
Considering these are different scenes and different flags altogether. Can you please upload your spoiler log, and as a quick question - did you replace the code.ips file when updating your seed and start a new save file?

Thanks!

**Comment by DiabloThePoet** [comment]
Attached should be my spoiler log. 

The seed I'm working on is actually the first and only seed I've generated for MM3dsr so far. Working on trying to beat it and reporting any issues I'm seeing along the way. The version of the randomizer that I am currently on is what the current version was when I first downloaded it a week ago. I did so by scanning the QR code. So whatever scanning the CIA QR code did in terms of setup is what I've done. 

[1347080933 (Letter To Mama, Deku Princess, Bomber's Notebook, Bombchu, Blast Mask)-spoilerlog.pdf](https://github.com/Z3DR/MM3D_Randomizer/files/14255337/1347080933.Letter.To.Mama.Deku.Princess.Bomber.s.Notebook.Bombchu.Blast.Mask.-spoilerlog.pdf)

**Comment by PhlexPlexico** [comment]
Hmm, it looks like that one was reported already and has been fixed as of 1.2.2. However there are a few new bugs that came along with that release that we're actively working on fixing. So I believe this should already be fixed :) thanks for the report! If you run into any others, feel free to let me know!

Thanks!

**Comment by PhlexPlexico** [comment]
Should be fixed as of https://github.com/Z3DR/MM3D_Randomizer/pull/44
