### ISSUE TITLE
Was Not Given Repeatable Quest Item Upon Second Time Completing Quest That Gave It To Me When I Completed It The First Time

### ISSUE THREAD

**Issue by DiabloThePoet** [Z3DR/MM3D_Randomizer#45]
The first time I completed the Romani Ranch Alien Defense quest, I was given the Ocean Title Deed. It is listed as a repeatable item for that quest in the item log, much like it is in the base game. Upon completing the quest for a second time, I was instead given a fishing hole pass and am now locked out of fully completing the Deku Merchant trade quest.

I've attached my spoiler log.

[1347080933 (Letter To Mama, Deku Princess, Bomber's Notebook, Bombchu, Blast Mask)-spoilerlog.pdf](https://github.com/Z3DR/MM3D_Randomizer/files/14273328/1347080933.Letter.To.Mama.Deku.Princess.Bomber.s.Notebook.Bombchu.Blast.Mask.-spoilerlog.pdf)

Current Version: v1.2.1

Seed Hash:
Letter To Mama
Deku Princess
Bomber's Notebook
Bombchu
Blast Mask

**Comment by PhlexPlexico** [comment]
This is actually intended design, however the ocean title deed shouldn't be placed there. But this will be fixed in a near upcoming release.

Thanks!

**Comment by DiabloThePoet** [comment]
On a similarish note, I had an instance occur where I had one of the land title deeds and then acquired the moon's tear, which overrode the title deed item slot. I went and gave the moon's tear to the Clock Town Deku scrub which normally would remove the moon's tear from your inventory and in my reasoning make the title deed that I had previously reappear, sort of how the trade items work in the OOT3D randomizer, but the moon's tear remained in my inventory, preventing me from accessing and using the title deed that I had previously received. 

Thought I could just describe the issue here since it is sort of similar instead of opening a whole new issue to describe it.

**Comment by PhlexPlexico** [comment]
Yes, and we already have that feature as a work in progress. Next second point release (1.3.0) will have this as a new feature.

Thanks!

**Comment by DiabloThePoet** [comment]
Okay great! Really enjoying the randomizer so far, quirks and all!

Thanks!
