### ISSUE TITLE
Bomb Bags

### ISSUE THREAD

**Issue by OakMastermind58** [Z3DR/MM3D_Randomizer#53]
If you collect a bomb bag before purchasing the bomb bag from the shop, the shopkeeper will not sell you the bomb bag and, if you have the big bomb bag before purchasing from the shop at all the shopkeeper won't sell any bomb bag to you.

**Comment by PhlexPlexico** [comment]
Hi,

I think you may have to explain a little bit here - Bomb bags currently aren't shuffled in the game, so what exactly are you doing to get this behaviour?

Thanks!

**Comment by OakMastermind58** [comment]
I can't remember where I got the big bomb bag, (it might be from the grandma robbery on the night of the first day) I've even looked though the tracker to see where I got the big bomb bag but it doesn't say. The tracker specifically calls out "WCT Bomb Bag Purchase", and "WCT Big Bomb Bag Purchase". and since I have the big bomb bag I can't purchase any bomb bag. Funny thing I didn't even get regular bomb bag first, but since it's not added yet I guess that is to be expected.

Sorry if I didn't explain it well here, I'm not exactly sure what to tell you. I can share the seed and hash if you like, I'm on version 1.2.3

LMK if you have any more questions, tx for making the rando though!

**Comment by OakMastermind58** [comment]
It won't let me upload the XML file, but changing a copy of it to a TXT file seems to work. I don't remember purchasing the bomb bag because I remember looking though the item tracker and seeing that the bomb shop was on there and I had only purchased bombchus. No I didn't mess with starting items at all, I was only doing a simple rando to test if it worked and to refresh my memory for item locations so I didn't make many drastic choices I think.

I hope this helps, lmk if you need more info.

[1839128492 (Ice Arrow, Gibdo Mask, Stone Mask, Mirror Shield, Ice Arrow)-spoilerlog.txt](https://github.com/Z3DR/MM3D_Randomizer/files/14381309/1839128492.Ice.Arrow.Gibdo.Mask.Stone.Mask.Mirror.Shield.Ice.Arrow.-spoilerlog.txt)

**Comment by PhlexPlexico** [comment]
Hmmm, well I'm not sure what to exactly say. There's not really a way to get bombs in a playthrough without actively receiving them from vanilla locations. Considering this is an older build as well, I think we may just have to put this issue on hold. I don't think I've had anyone else report this as well, either.
