### ISSUE TITLE
Gold Dust Not Respawning Even Though Listed As Repeatable Item

### ISSUE THREAD

**Issue by DiabloThePoet** [Z3DR/MM3D_Randomizer#62]
Not sure if this issue has been brought up before, but I cannot get the gold dust to respawn inside of the Termina Field grass chest where I found it the first time. After resetting the day cycle, I now only get a blue rupee from the chest and now seemingly have no way of obtaining the gold dust again to complete the mountain smithy quest. This quest seems to be the only one I could potentially currently do, thus not being able to obtain the gold dust again has softlocked me to the best of my knowledge. 

I'm on version 1.2.3

**Comment by PhlexPlexico** [comment]
Hi,

Please check the release notes of the latest nightly. There's been a laundry list of changes, and bottle contents + repeatable items has been reworked quite extensively, so you will not run into this problem anymore :)

Thanks!
