### ISSUE TITLE
Invalid Starting Inventory options

### ISSUE THREAD

**Issue by CharadeNut** [Z3DR/MM3D_Randomizer#79]
These Starting Inventory options don't work as intended:
• Bow + Quiver (50): Only gives Quiver (30)
• Bow + Quiver (40): Only gives Quiver (30)
• Bomb Bag (40): Only gives Bomb Bag (20)
• Bomb Bag (30): Only gives Bomb Bag (20)
• Tycoon Wallet: Only gives Giant Wallet
Note: Having Deku Nuts, Deku Sticks, etc. on gives you the max amount anyway, so "Start with Consumables" is redundant

**Comment by PhlexPlexico** [comment]
Tycoon wallet isn't actually in the game itself, it's reserved for a future setting.

As for the start with max consumables, that also maxes out your rupees, does it not?

**Comment by CharadeNut** [comment]
There's a separate option to start with maxed out rupees.

**Comment by PhlexPlexico** [comment]
Latest nightly should resolve these issues now! Thanks for the report @CharadeNut  :)
