### ISSUE TITLE
Powder keg not respawning

### ISSUE THREAD

**Issue by thejhnsn** [Z3DR/MM3D_Randomizer#86]
I found the powder keg in Snowhead Temple, used it and next cycle when I tried to get it again, the chest in Snowhead temple just gave me a blue rupee. I can't buy the powder keg in WCT either as I don't have the certificate needed (can't even find the certificate in the spoiler log).

Randomizer version: v1.3.1-6be4ef
Spoiler log: [1948720841 (Kafei Mask, Kamaro Mask, Great Fairy Mask, Deku Stick, Couple's Mask)-spoilerlog.txt](https://github.com/Z3DR/MM3D_Randomizer/files/14888312/1948720841.Kafei.Mask.Kamaro.Mask.Great.Fairy.Mask.Deku.Stick.Couple.s.Mask.-spoilerlog.txt)

**Comment by RandoZLink** [comment]
This is intended behavior, you need to wear Goron Mask and talk to the Goron in the Bomb Shop in order to repurchase the Powder Keg as the game checks to see if you have at least gotten your first Keg to let you buy them from the Goron. Powder Keg "Certification" is not a real item in the game.

**Comment by thejhnsn** [comment]
Ah I see, thanks for the quick response!
