### ISSUE TITLE
Saved presets not working properly

### ISSUE THREAD

**Issue by CKingsinn** [Z3DR/MM3D_Randomizer#95]
Since installing this version (1.3.3-fde349), my saved presets are not working and my randomizer settings are always defaulted no matter what I change. I have even tried a fresh reinstall and am still getting default settings on my new presets.

**Comment by PhlexPlexico** [comment]
Hi,

Thanks for the report! We've been fighting a key that actually contains a null value. If you're able to, open up your saved presets located at `3ds/presets/mm3dr/settings/` and on line 10, change the following
```<setting name="  Language"></setting>```
to
```<setting name="  Language">English</setting>```

And this should fix the issue for now. We're working on trying to get this fixed asap.

Thanks!

**Comment by PhlexPlexico** [comment]
Alright, would you mind trying this nightly and see if your presets load without modifications?

https://github.com/Z3DR/MM3D_Randomizer/releases/tag/Nightly-707574

Thanks!

**Comment by CKingsinn** [comment]
I apologize heavily for the very delayed response I was a bit busy and completely forgot to check this thread when I had time. That linked nighly build works perfectly, thank you!
