### ISSUE TITLE
Gets stuck on a black 3ds loading screen

### ISSUE THREAD

**Issue by Gloomy1111** [Z3DR/MM3D_Randomizer#99]
After I randomize the game, it will only show a black screen with the 3ds logo, it never loads. This is the physical copy and Luma3ds is up to date. Anybody know a solution?
![20240607_095329](https://github.com/Z3DR/MM3D_Randomizer/assets/117923035/41f6e7f2-d742-4700-a13a-876d0d77df3a)

**Comment by PhlexPlexico** [comment]
Any update towards this?

**Comment by PhlexPlexico** [comment]
Closing as there was no response. If there are still issues, feel free to re-open. Thanks!

**Comment by PDuckGit** [comment]
He ended up fixing it, sorry for not responding
